### ISSUE TITLE
scala.MatchError: 1 (of class java.lang.Long) Exception.

### ISSUE THREAD

**Issue by shashi4414** [ZuInnoTe/hadoopoffice#16] opened 2017-07-07 11:01 UTC
Hello.
             df.repartition(1).write()
	           .mode(SaveMode.Overwrite)
	           .format("org.zuinnote.spark.office.excel")
	           .option("write.locale.bcp47", "de")
	           .save("C:\\path\\NEWFILE1.xlsx");
We are getting exception “scala.MatchError: 1 (of class java.lang.Long)” when we write the data frame to excel,
The dataset object  df is row type is it necessary to change it into String dataset  or it can write in row type.
 please help me..

**Comment by jornfranke** [comment] 2017-07-07 11:04
It should be able to do long, it might that you still have the old version ...

**Comment by shashi4414** [comment] 2017-07-07 11:12
we are using this version  
 <dependency>
               <groupId>com.github.zuinnote</groupId>
               <artifactId>spark-hadoopoffice-ds_2.11</artifactId>
                <version>1.0.3</version>
                </dependency>

**Comment by jornfranke** [comment] 2017-07-07 12:05
Ok maybe I was not clear it will be fixed in version 1.0.4 which is available end of July. You can however test the source code in git Spark-hadoopoffice-ds to verify that it works.

**Comment by shashi4414** [comment] 2017-07-07 15:53
Sorry there is a confusion, Is the issue fixed or not, IF fixed will it be available in version 1.0.4 ?

**Comment by jornfranke** [comment] 2017-07-07 16:20
Fixed in version 1.0.4 you can check it out in Git, build it yourself and test it. Or wait for end of July.

**Comment by jornfranke** [comment] 2017-07-31 22:11
duplicate of https://github.com/ZuInnoTe/hadoopoffice/issues/15

**Closed by jornfranke** 2017-07-31 22:11 UTC
Labels: duplicate
